services:
  node:
    container_name: node
    build:
        dockerfile: ./docker/node.Dockerfile
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '8080:8080'
    volumes:
      - ./:/home
      - ./.aws.credentials:/root/.aws/credentials
